;====================================================================
; Main.asm file generated by New Project wizard
/* =====================================
exemplo programa com interrupcao TC0 - timer 0 ,
MODO NORMAL
estouro em FF(255)  contagem em TCNT0 valor inicial

*/
;====================================================================
; DEFINITIONS
;====================================================================
.equ vermelho = pb0
.equ amarelo = pb1
.equ verde = pb2
;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================
.org 0x0000        ; Reset Vector
      rjmp  Start
.org 0x0020  ; overflow de tcnt0 valor top
     rjmp TIM0_OV    

.org 0x050		
;====================================================================
; CODE SEGMENT
;====================================================================
.include "lib328Pv01.inc"
Start:
      ; Write your code here
	sbi ddrd,5
	sbi ddrd,6
	sbi ddrb,0
	sbi ddrb,1
	sbi ddrb,2 

	ldi r16,120  ;  ativa pinos 0C0A E 0C0B com mudan�a na igualdade, operacao TC0 modo NORMAL
	out OCR0A,r16

	ldi r16,120  ;  ativa pinos 0C0A E 0C0B com mudan�a na igualdade, operacao TC0 modo NORMAL
	out OCR0B,r16


   ldi r16,0b01010000  ;  ativa pinos 0C0A E 0C0B com mudan�a na igualdade, operacao TC0 modo NORMAL
	out TCCR0A,r16
	
	/* TCCR0A  Registrador de controle A do TC0  
	COM0A1 COM0A0 COM0B1 COM0B0  -     -     WGM01 WGM00
	 7        6     5      4     3     2       1     0

	 COM0A1 COM0A0 controlam o comportamento do pino 0C0A pino D6 (modos normal, CTC, pwm rapido)
	   0      0  - pino 0C0A desconectado
	   0      1  - mudanca de estado na igualdade (modo normal)
	   1      0  - aterrado na igualdade(modo normal/pwm rapido) =0 crescente e =1 decrescente (pwm fase corrigida)
	   1      1  - Ativo  na igualdade (modo normal/pwm rapido) =1 crescente e =0 decrescente (pwm fase corrigida)

	   COM0B1 COM0B0  controlam o comportamento do pino 0C0B  pino D5
	   0      0  - pino 0C0B desconectado
	   0      1  - mudanca de estado na igualdade (modo normal)
	   1      0  - aterrado na igualdade (modo normal/pwm rapido) =0 crescente e =1 decrescente (pwm fase corrigida)
	   1      1  - Ativo  na igualdade (modo normal/pwm rapido) =1 crescente e =0 decrescente (pwm fase corrigida)

	   WGM02 WGM01 WGM00 bits do modo de controle, fonte do valor maximo e forma de onda
	   0     0     0  - normal     TOP em FF
	   0     0     1  - pwm fase corrigida top em FF
	   0     1     0  - CTC        TOP em 0CR0A
	   0     1     1  - pwm rapido  TOP em FF
	   1     0     0  - 
	   1     0     1  - pwm fase corrigida top em 0CR0A
	   1     1     0   -
	   1     1     1  - pwm rapido TOP em 0CR0A
	*/

	ldi r16,0b00000001  ; se habilitar interrupcao por overflow 
	sts TIMSK0,r16 
	/* TIMSK0 Interruptor de mascara do contador TC0
	- - - - - 0CIE0B 0CIE0A TOIE0
	7 6 5 4 3   2      1      0
	0CIE0B ativa a interrup��o na igualdade de compara��o 0CR0B
	0CIE0A ativa a interrup��o na igualdade de compara��o 0CR0A
	TOIE0  ativa a interrup��o de estouro em TOP=FF

	*/

	ldi r16,0b00000101
	out TCCR0B,r16   ; prescaler 1024
	/* TCCR0B  Registrador de controle B do TC0
	F0C0A  FOC0B   -    -   WGM02  CS02  CS01  CS00
	7        6     5    4     3      2    1      0

	CS02  CS01  CS00  bits de selecao do prescaler
	   0     0     0  - sem fonte de clock tc0 parado
	   0     0     1  - prescaler =1
	   0     1     0  - prescaler = 8
	   0     1     1  - prescaler = 64
	   1     0     0  - prescaler = 256
	   1     0     1  - prescaler = 1024
	   1     1     0  - clock externo pino T0 (pd4) contagem borda descida
	   1     1     1  - clock externo pino T0 (pd4) contagem borda subida     
	*/

	ldi r16,100
	out TCNT0,r16   ; valor inicial do TC0  
    sei ; habilita as interrup��es no microcontrolador


Loop:
  ; codigo principal 

  ;;;;;;
    rjmp  Loop

	
;==============================================================	
; rotina executada em overflow de tcnt0
TIM0_OV:
	ldi r16,100
	out TCNT0,r16   ; valor inicial do TCNT0
	sbic portb,1
	rjmp apagaled
	sbi portb,1
	reti
apagaled: ; pisca o amarelo
    cbi portb,1
	reti	
