;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   seg nov 9 2015
; Processor: ATmega328P
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS

; VARIABLES
;====================================================================
.def caixas = r0


      ; Reset Vector
      rjmp  INICIO

;====================================================================
; CODE SEGMENT
;====================================================================
.include biblioteca.inc"
INICIO:


	rcall lcd_init	; Inicializaçăo do LCD (VSS=GND VDD=5V VO=GND RS=PD2 RW=GND E=PD3  
                        ;  D4=PD4 D5=PD5 D6=PD6 D7=PD7 A=5V K=GND) 
loop:
	rcall lcd_clear	; Chama rotina limpar o LCD e posicionar na linha 0, coluna 0
	
	ldi lcd_col,3 ;define coluna3
	rcall lcd_lin0_col ;define linha 0
	
	ldi lcd_caracter,'C'			
	rcall lcd_write_caracter				
	ldi lcd_caracter,'A'
	rcall lcd_write_caracter
	ldi lcd_caracter,'R'
	rcall lcd_write_caracter
	ldi lcd_caracter,'R'
	rcall lcd_write_caracter
	ldi lcd_caracter,'E'
	rcall lcd_write_caracter
	ldi lcd_caracter,'G'
	rcall lcd_write_caracter
	ldi lcd_caracter,'A'
	rcall lcd_write_caracter
	ldi lcd_caracter,'N'
	rcall lcd_write_caracter
	ldi lcd_caracter,'D'
	rcall lcd_write_caracter
	ldi lcd_caracter,'O'
	rcall lcd_write_caracter
	
	ldi lcd_col,0 ; define coluna 0
	rcall lcd_lin1_col ; define linha 1,coluna 0
	
	ldi lcd_caracter,'C'			
	rcall lcd_write_caracter				
	ldi lcd_caracter,'A'
	rcall lcd_write_caracter
	ldi lcd_caracter,'I'
	rcall lcd_write_caracter
	ldi lcd_caracter,'X'
	rcall lcd_write_caracter
	ldi lcd_caracter,'A'
	rcall lcd_write_caracter
	ldi lcd_caracter,'S'
	rcall lcd_write_caracter
	ldi lcd_caracter,'='
	rcall lcd_write_caracter
	
	
	mov lcd_number,caixas
	rcall lcd_write_number
        inc caixas
	ldi delay_time,1			
	rcall delay_seconds

        rjmp loop

